"use client";

import type { ComponentProps } from "react";
import {
  WhatsappLogo,
  Phone,
  EnvelopeSimple,
  MapPin,
  ArrowRight,
  ArrowUpRight,
  List,
  X,
  Sun,
  Moon,
  Check,
  CheckCircle,
  Wrench,
  ShieldCheck,
  Shield,
  CalendarDots,
  MapTrifold,
  Gear,
  Factory,
  Truck,
  Handshake,
  FileText,
  CaretRight,
  CaretDown,
  Plug,
  Gauge,
  Drop,
  Snowflake,
  Funnel,
  CircleNotch,
  PaperPlaneTilt,
  Warning,
  Info,
  Wind,
  Link as LinkIcon,
  Image as ImageIcon,
  Cube,
  Lightning,
  Headset,
  Lock,
} from "@phosphor-icons/react";

/**
 * Standardized Phosphor icon re-exports.
 * Stroke weight is locked to `regular` for line icons and `bold` only where
 * explicitly needed, keeping the icon language consistent across the site.
 * We deliberately avoid emoji — every glyph here is a vector icon.
 */
export {
  WhatsappLogo,
  Phone,
  EnvelopeSimple,
  MapPin,
  ArrowRight,
  ArrowUpRight,
  List,
  X,
  Sun,
  Moon,
  Check,
  CheckCircle,
  Wrench,
  ShieldCheck,
  Shield,
  CalendarDots,
  MapTrifold,
  Gear,
  Factory,
  Truck,
  Handshake,
  FileText,
  CaretRight,
  CaretDown,
  Plug,
  Gauge,
  Drop,
  Snowflake,
  Funnel,
  CircleNotch,
  PaperPlaneTilt,
  Warning,
  Info,
  Wind,
  LinkIcon,
  ImageIcon,
  Cube,
  Lightning,
  Headset,
  Lock,
};

export type IconProps = ComponentProps<typeof ArrowRight>;
